### ISSUE TITLE
[settings.py] remove postgres database link

### ISSUE THREAD

**Issue by romebell** [mike-gustafson/mysite#1]
https://github.com/mike-gustafson/mysite/blob/29d0cfa5b9717afc1a0b5778d0a05ae5bea2857f/mysite/settings.py#L31

- [ ] remove Heroku Postgres database link from being exposed publicly.

**Comment by mike-gustafson** [comment]
was having issues with secrets so I hardcoded it for testing purposes.  it's been removed and will go away in the next push
